/* Generated by Claude 3.5 Sonnet */

document.addEventListener('DOMContentLoaded', function() {
    const isMobile = window.innerWidth <= 767;
    
    if (isMobile) {
        initMobileLayout();
    }
    
    window.addEventListener('resize', function() {
        const newIsMobile = window.innerWidth <= 767;
        if (newIsMobile !== isMobile) {
            location.reload();
        }
    });
});

function initMobileLayout() {
    createMobileButtons();
    createOverlay();
    addEventListeners();
}

function createMobileButtons() {
    const header = document.querySelector('header');
    
    const menuBtn = document.createElement('button');
    menuBtn.className = 'mobile-menu-toggle';
    menuBtn.innerHTML = '<i class="fas fa-bars"></i>';
    header.appendChild(menuBtn);
    
    const sidebarBtn = document.createElement('button');
    sidebarBtn.className = 'mobile-sidebar-toggle';
    sidebarBtn.innerHTML = '<i class="fas fa-cog"></i>';
    header.appendChild(sidebarBtn);
    
    createMobileUserProfile();
}

function createMobileUserProfile() {
    const nav = document.querySelector('nav');
    
    
    fetch('../phps/auth.php')
        .then(response => response.json())
        .then(data => {
            if (data.loggedin) {
                const userProfile = document.createElement('div');
                userProfile.className = 'mobile-user-profile';
                
                const mobileAvatar = document.createElement('img');
                mobileAvatar.className = 'mobile-user-avatar';
                mobileAvatar.src = data.user_avatar || '../images/default_avatar.jpeg';
                mobileAvatar.alt = 'User avatar';
                
                const mobileName = document.createElement('p');
                mobileName.className = 'mobile-user-name';
                mobileName.textContent = data.username;
                
                const profileLink = document.createElement('a');
                profileLink.href = 'profile.html';
                profileLink.style.textDecoration = 'none';
                profileLink.style.color = 'inherit';
                profileLink.appendChild(mobileAvatar);
                profileLink.appendChild(mobileName);
                
                const logoutBtn = document.createElement('a');
                logoutBtn.addEventListener('click', function(e) {
                    e.preventDefault(); 
                    // Send a request to the server to log out the user
                    fetch('../phps/logout.php')
                        .then(response => response.json()) 
                        .then(data => {
                            console.log('Response:', data);  
                            if (data.success) {
                                window.location.href = data.redirect;
                                console.log('Logout successful:', data.message);
                            } else {
                                console.error('Logout failed:', data.error);
                            }
                        })
                        .catch(error => {
                            console.error('Error:', error);
                        });
                })
                logoutBtn.className = 'mobile-logout-btn';
                logoutBtn.textContent = 'Logout';
                
                userProfile.appendChild(profileLink);
                userProfile.appendChild(logoutBtn);
                nav.insertBefore(userProfile, nav.firstChild);
            }
        })
        .catch(error => {
            console.error('Failed to fetch user data:', error);
        });
}

function createOverlay() {
    const overlay = document.createElement('div');
    overlay.className = 'mobile-overlay';
    document.body.appendChild(overlay);
}

function addEventListeners() {
    const menuBtn = document.querySelector('.mobile-menu-toggle');
    menuBtn.addEventListener('click', toggleNav);
    
    const sidebarBtn = document.querySelector('.mobile-sidebar-toggle');
    sidebarBtn.addEventListener('click', toggleSidebar);
    
    const overlay = document.querySelector('.mobile-overlay');
    overlay.addEventListener('click', hideAll);
    
    document.addEventListener('keydown', function(e) {
        if (e.key === 'Escape') {
            hideAll();
        }
    });
}

function toggleNav() {
    const nav = document.querySelector('nav');
    const overlay = document.querySelector('.mobile-overlay');
    const sidebar = document.querySelector('aside');
    
    if (nav.classList.contains('show')) {
        nav.classList.remove('show');
        overlay.classList.remove('show');
    } else {
        nav.classList.add('show');
        overlay.classList.add('show');
        sidebar.classList.remove('show');
    }
}

function toggleSidebar() {
    const sidebar = document.querySelector('aside');
    const overlay = document.querySelector('.mobile-overlay');
    const nav = document.querySelector('nav');
    
    if (sidebar.classList.contains('show')) {
        sidebar.classList.remove('show');
        overlay.classList.remove('show');
    } else {
        sidebar.classList.add('show');
        overlay.classList.add('show');
        nav.classList.remove('show');
    }
}

function hideAll() {
    const nav = document.querySelector('nav');
    const sidebar = document.querySelector('aside');
    const overlay = document.querySelector('.mobile-overlay');
    
    nav.classList.remove('show');
    sidebar.classList.remove('show');
    overlay.classList.remove('show');
}

window.addEventListener('orientationchange', function() {
    setTimeout(hideAll, 100);
});

window.mobileUtils = {
    toggleNav: toggleNav,
    toggleSidebar: toggleSidebar,
    hideAll: hideAll
}; 